{% set name = "monetio" %}
{% set version = "0.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e1488093f69380cc0b07e37da092a474a7f004e0d6b9b7b3d0c11d3cf0181be5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    #
    - dask
    - h5netcdf
    - joblib
    - lxml
    - netcdf4
    - numpy
    - pandas
    - pyresample
    - requests
    - s3fs
    - scipy
    - xarray

test:
  imports:
    - monetio
    - monetio.models
    - monetio.obs
    - monetio.profile
    - monetio.sat

about:
  home: https://monetio.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/noaa-oar-arl/monetio
  summary: The Model and ObservatioN Evaluation Tool - Input / Output

extra:
  recipe-maintainers:
    - zmoon
    - bbakernoaa
