{% set name = "monetio" %}
{% set version = "0.2.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f12da343ec15aafdb7925df68a240ebb97036a29770233c1757c431ea2a826a5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    #
    - dask
    - h5netcdf
    - h5py
    - joblib
    - lxml
    - netcdf4
    - numpy
    - pandas
    - pyresample
    - requests
    - s3fs
    - scipy
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - monetio
    - monetio.models
    - monetio.obs
    - monetio.profile
    - monetio.sat

about:
  home: https://monetio.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/noaa-oar-arl/monetio
  summary: The Model and ObservatioN Evaluation Tool - Input / Output

extra:
  recipe-maintainers:
    - zmoon
    - bbakernoaa
